Repository Azure/open-service-broker-azure, pull requests merged in 2018-05, with the labels that each got.

#423 make postgres and mysql provisioning schemas tier-specific
  pkg/services/mysql/all_in_one_provision_test.go
  pkg/services/mysql/catalog.go
  pkg/services/mysql/common_provision.go
  pkg/services/mysql/plan_schemas.go
  pkg/services/postgresql/all_in_one_provision_test.go
  pkg/services/postgresql/catalog.go
  pkg/services/postgresql/common.go
  pkg/services/postgresql/common_provision.go
  pkg/services/postgresql/database_types.go
  pkg/services/postgresql/plan_schemas.go
Labels: high priority

#425 Add OpenShift template
  README.md
  contrib/openshift/osba-os-template.yaml
Labels: documentation

#445 improve schema-drive validations
  pkg/service/catalog_test.go
  pkg/service/schema.go
  pkg/service/schema_test.go
  pkg/services/fake/catalog.go
Labels: bug

#456 add missing early return from api provisioning
  pkg/api/provision.go
Labels: bug
