Repository Azure/open-service-broker-azure, pull requests merged in 2018-04, with the labels that each got.

#369 use container executors only in circle
  .circleci/config.yml
  Makefile
  docker-compose.yml
  pkg/async/redis/cleaner_test.go
  pkg/async/redis/engine_test.go
  pkg/storage/store_test.go
  tests/api-compliance/broker-config.json
  tests/api-compliance/localhost-config.json
  tests/api-compliance/scripts/test.sh
  tests/api-compliance/scripts/wupiao.sh
Labels: refactor

#346 Adding explanation of stability and semver
  docs/roadmap.md
  docs/stability.md
Labels: documentation

#350 move redis-based storage to its own package
  cmd/broker/broker.go
  pkg/storage/redis/config.go
  pkg/storage/redis/store.go
  pkg/storage/redis/store_test.go
  pkg/storage/store.go
Labels: refactor

#377 DRY up yaml a bunch
  .circleci/config.yml
  docker-compose.yml
Labels: refactor

#382 fix release process
  .circleci/config.yml
  Makefile
Labels: bug

#388 fix default environment in chart
  contrib/k8s/charts/open-service-broker-azure/README.md
  contrib/k8s/charts/open-service-broker-azure/values.yaml
Labels: bug

#394 Added some words about stability and the helm chart
  docs/faq.md
  docs/quickstart-aks.md
  docs/quickstart-minikube.md
Labels: documentation

#408 Adding required version info to docs
  docs/faq.md
  docs/quickstart-aks.md
  docs/quickstart-minikube.md
Labels: documentation

#419 update postgresql and mysql plan descriptions
  pkg/services/mysql/catalog.go
  pkg/services/postgresql/catalog.go
Labels: high priority

#418 Updated CF example to include firewall rules
  README.md
  contrib/cf/README.md
Labels: documentation
