Repository Azure/open-service-broker-azure, pull requests merged in 2018-03, with the labels that each got.

#318 Quickstart updates
  docs/quickstart-aks.md
  docs/quickstart-minikube.md
Labels: documentation

#316 Lots of changes to the module documentation and the contrib examples
  contrib/doc-templates/module.md
  contrib/k8s/examples/cosmosdb/cosmosdb-bindings.yaml
  contrib/k8s/examples/cosmosdb/cosmosdb-instance.yaml
  contrib/k8s/examples/mysql/README.md
  contrib/k8s/examples/mysql/advanced/mysql-database-binding.yaml
  contrib/k8s/examples/mysql/advanced/mysql-database-instance.yaml
  contrib/k8s/examples/mysql/advanced/mysql-dbms-instance.yaml
  contrib/k8s/examples/mysql/mysql-binding.yaml
  contrib/k8s/examples/mysql/mysql-instance.yaml
  contrib/k8s/examples/mysqldb-binding.yaml
  contrib/k8s/examples/postgresql/README.md
  contrib/k8s/examples/postgresql/advanced/postgresql-database-binding.yaml
  contrib/k8s/examples/postgresql/advanced/postgresql-database-instance.yaml
  contrib/k8s/examples/postgresql/advanced/postgresql-dbms-instance.yaml
  contrib/k8s/examples/postgresql/postgresql-binding.yaml
  contrib/k8s/examples/postgresql/postgresql-instance.yaml
  contrib/k8s/examples/redis/rediscache-binding.yaml
  contrib/k8s/examples/redis/rediscache-instance.yaml
  contrib/k8s/examples/sql/README.md
  contrib/k8s/examples/sql/advanced/sql-database-instance-binding.yaml
  contrib/k8s/examples/sql/advanced/sql-database-instance.yaml
  contrib/k8s/examples/sql/advanced/sql-dbms-instance.yaml
  contrib/k8s/examples/sql/sql-binding.yaml
  contrib/k8s/examples/sql/sql-instance.yaml
  contrib/k8s/examples/sqldb/README.md
  contrib/k8s/examples/sqldb/sqldb-all-in-one-binding.yaml
  docs/modules/mssql.md
  docs/modules/mysql.md
  docs/modules/postgresql.md
  pkg/services/mssql/catalog.go
  pkg/services/mysql/catalog.go
  pkg/services/postgresql/catalog.go
Labels: documentation

#330 move configs around
  cmd/broker/broker.go
  cmd/broker/modules.go
  docker-compose.yml
  pkg/api/basic_auth_config.go
  pkg/api/basic_auth_config_errors.go
  pkg/api/basic_auth_config_test.go
  pkg/async/redis/config.go
  pkg/azure/config.go
  pkg/crypto/config.go
  pkg/log/config.go
  pkg/service/modules_config.go
  pkg/storage/redis_config.go
  tests/lifecycle/groups_client_test.go
  tests/lifecycle/keyvault_cases_test.go
  tests/lifecycle/test_cases_test.go
Labels: do not merge

#335 Link to upstream svcat install instructions
  README.md
Labels: documentation

#336 updated the path of postgresql example
  README.md
Labels: documentation

#340 Add FAQ
  README.md
  docs/faq.md
Labels: documentation

#345 Removing exclamation marks from docs
  README.md
  docs/modules/aci.md
  docs/modules/cosmosdb.md
  docs/modules/eventhubs.md
  docs/modules/keyvault.md
  docs/modules/mssql.md
  docs/modules/mysql.md
  docs/modules/postgresql.md
  docs/modules/rediscache.md
  docs/modules/search.md
  docs/modules/servicebus.md
  docs/modules/storage.md
Labels: documentation

#341 refactor how storage gets its encryption codec
  cmd/broker/broker.go
  contrib/cf/README.md
  contrib/cf/manifest.yml
  docker-compose.yml
  pkg/crypto/config.go
  pkg/storage/config.go
  pkg/storage/store.go
  pkg/storage/store_test.go
Labels: refactor

#342 clean up azure config
  cmd/broker/broker.go
  cmd/broker/modules.go
  pkg/azure/config.go
  pkg/broker/broker.go
  pkg/broker/broker_test.go
  tests/lifecycle/groups_client_test.go
  tests/lifecycle/keyvault_cases_test.go
  tests/lifecycle/test_cases_test.go
Labels: refactor

#358 add go report card badge
  README.md
Labels: documentation

#351 refactor lifecycle tests
  cmd/broker/broker.go
  pkg/boot/catalog.go
  pkg/boot/modules.go
  pkg/service/catalog_config.go
  pkg/services/eventhubs/eventhub.go
  pkg/services/search/search.go
  tests/lifecycle/aci_cases_test.go
  tests/lifecycle/cosmosdb_cases_test.go
  tests/lifecycle/driver_test.go
  tests/lifecycle/eventhub_cases_test.go
  tests/lifecycle/keyvault_cases_test.go
  tests/lifecycle/mssql_cases_test.go
  tests/lifecycle/mysql_cases_test.go
  tests/lifecycle/postgresql_cases_test.go
  tests/lifecycle/rediscache_cases_test.go
  tests/lifecycle/search_cases_test.go
  tests/lifecycle/servicebus_cases_test.go
  tests/lifecycle/storage_cases_test.go
  tests/lifecycle/test_case_test.go
  tests/lifecycle/test_cases_test.go
Labels: refactor

#360 use docker multistage build to build binary and image
  .circleci/config.yml
  Dockerfile
  Makefile
  ca-certificates.crt
Labels: refactor

#355 Add JSON Schema to Catalog
  pkg/service/catalog.go
  pkg/service/catalog_test.go
  pkg/service/schema.go
  pkg/services/aci/catalog.go
  pkg/services/aci/types.go
  pkg/services/keyvault/catalog.go
  pkg/services/keyvault/types.go
  pkg/services/mssql/all_in_one_types.go
  pkg/services/mssql/catalog.go
  pkg/services/mssql/common_types.go
  pkg/services/mssql/database_types.go
  pkg/services/mssql/dbms_types.go
  pkg/services/mysql/all_in_one_types.go
  pkg/services/mysql/catalog.go
  pkg/services/mysql/common_types.go
  pkg/services/mysql/database_types.go
  pkg/services/mysql/dbms_types.go
  pkg/services/postgresql/all_in_one_types.go
  pkg/services/postgresql/catalog.go
  pkg/services/postgresql/common_types.go
  pkg/services/postgresql/database_types.go
  pkg/services/postgresql/dbms_types.go
Labels: enhancement

#365 refactor Makefile
  Makefile
Labels: refactor

#368 Fix the broken doc links
  README.md
Labels: documentation
